### PR TITLE
Specify Content-Length header on responses

### PR DESCRIPTION
**Pull request by joefiorini**

### CODE REVIEW

**Comment by ahawkins** [comment]
Doesn't Rack set this header if it's not set?

**Comment by joefiorini** [comment]
It wasn't for me, maybe I need to wrap my middleware in Rack::Lint. I'll
try that and close if that fixes it.

**Comment by joefiorini** [comment]
I'm not using the middleware anymore, so I'm going to close this.

**Comment by joefiorini** [comment]
Also worth mentioning that @twinturbo was correct, Rack does set it automatically. Don't know why I had issues with this originally, but it's all good now.

**Pull request closed without merging**
